#-------------
# My Github Actions lesson
#-------------

name: My_Actions_basics
env :
  APP_NAME    : "My_Test_proj"
  DEPLOY_PACKAGE_NAME : "prog_deploy_ver_${{ github.sha }}"

on: 
  push:
    branches: 
      - main

jobs:
  test_job_1:
    runs-on: ubuntu-latest

    steps:
    - name: Printing_something
      run : |
        echo "Hi"
        echo "Your dpn is ${{ env.DEPLOY_PACKAGE_NAME }}"
        echo "This app name is ${{ env.APP_NAME }}"
    
    - name: List current_f
      run : |
        ll
        echo "Is there something files above?"

    - name: Clone current_r
      uses: actions/checkout@v1

    - name: List current_f_attempt2
      run : |
        ll
        echo "Is there something files above?"

  build_job_1:
    runs-on: ubuntu-latest
    needs: [test_job_1]

    steps:
    - name: Printing_in_build
      run : echo "Bye in build"

    - name: Test some packages if it is here
      run : aws --version

    - name: Some file with text
      run : echo "i'm lazy" > file1.txt

    - name: list cf
      run : |
        ls
        cat file1.txt
