#-------------
# My Github Actions lesson
#-------------

name: My_Actions_basics

on:
  push:
    branches: 
      - main

jobs:
  test_job_1:
    runs-on: ubuntu-latest

    steps:
    - name: Printing_something
      run : echo "Hi"
