#-------------
# My Github Actions lesson
#-------------

name: My_Actions_basics
env :
  APP_NAME    : "My_Test_proj"
  DEPLOY_PACKAGE_NAME : "prog_deploy_ver_${{ github.sha }}"

on: 
  push:
    branches: 
      - main

jobs:
  test_job_1:
    runs-on: ubuntu-latest

    steps:
    - name: Printing_something
      run : |
        echo "Hi"
        echo "Your dpn is ${{ env.DEPLOY_PACKAGE_NAME }}"
        echo "This app name is ${{ env.APP_NAME }}"


  build_job_1:
    runs-on: ubuntu-latest
    needs: [test_job_1]

    steps:
    - name: Printing_in_build
      run : echo "Bye in build"
